

spring:
  cloud:
    ## 整合sentinel，配置sentinel控制台的地址
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        ## 指定控制台的地址，默认端口8080
        dashboard: localhost:8080

      #配置限流之后，响应内容
      scg:
        fallback:
          ## 两种模式，一种是response返回文字提示信息，一种是redirect，重定向跳转，需要同时配置redirect(跳转的uri)
          # 方式1
          mode: response
          ## 响应的状态
          response-status: 200
          ## 响应体
          response-body: '{"code": 200,"message": "请求失败，稍后重试啊！"}'
      #     # # 方式2
      #     # mode: redirect
      #     # ## 跳转的URL
      #     # redirect: http://www.baidu.com

    gateway:
      # 路由
      routes:
        - id: foo-modules
          uri: lb://foo-modules
          predicates:
            - Path=/foo-modules/**

        - id: foo-auth
          uri: lb://foo-auth
          predicates:
            - Path=/foo-auth/**



        # - id: foo-modules
        #   uri: lb://foo-modules
        #   predicates:
        #     - Custom=ok

enable:
  # 是否开启黑名单，默认关闭
  blackList: false
  # 是否开启鉴权过滤器，默认开启
  auth: false







